###requisição para a raiz
GET http://localhost:5086/
### requisição para a funcionalidade com GET
GET http://localhost:5086/funcionalidade
### requisição para a funcionalidade com POST
POST http://localhost:5086/funcionalidade