### Requisição para a raiz
GET http://localhost:5011/

### Requisição para a lista de produtos
GET http://localhost:5011/api/produto/listar

### Buscar produto por nome
GET http://localhost:5011/api/produto/buscar/Teclado

### Remover produto por nome
DELETE http://localhost:5011/api/produto/remover/Teclado

### Alterar produto
PUT http://localhost:5011/api/produto/alterar/Monitor
Content-Type: application/json
{
    "nome" : "Monitor",
    "quantidade" : 20 ,
    "preco" : 850.0
}

### Requisição para POST
POST http://localhost:5011/api/produto/cadastrar
Content-Type: application/json
{
    "nome" : "Notebook",
    "quantidade" : 11 ,
    "preco" : 1450.5
}